#include <AL/alc.h>
#include <AL/alext.h>
#include <AL/al.h>

void alw_init(void);

extern void (*alwAuxiliaryEffectSlotf)(ALuint effectslot, ALenum param, ALfloat value);
extern void (*alwAuxiliaryEffectSlotfv)(ALuint effectslot, ALenum param, const ALfloat *pflValues);
extern void (*alwAuxiliaryEffectSloti)(ALuint effectslot, ALenum param, ALint iValue);
extern void (*alwAuxiliaryEffectSlotiv)(ALuint effectslot, ALenum param, const ALint *piValues);
extern void (*alwBuffer3f)(ALuint buffer, ALenum param, ALfloat value1, ALfloat value2, ALfloat value3);
extern void (*alwBuffer3i)(ALuint buffer, ALenum param, ALint value1, ALint value2, ALint value3);
extern void (*alwBufferData)(ALuint buffer, ALenum format, const ALvoid *data, ALsizei size, ALsizei freq);
extern void (*alwBufferf)(ALuint buffer, ALenum param, ALfloat value);
extern void (*alwBufferfv)(ALuint buffer, ALenum param, const ALfloat *values);
extern void (*alwBufferi)(ALuint buffer, ALenum param, ALint value);
extern void (*alwBufferiv)(ALuint buffer, ALenum param, const ALint *values);
extern void (*alwDeleteAuxiliaryEffectSlots)(ALsizei n, const ALuint *effectslots);
extern void (*alwDeleteBuffers)(ALsizei n, const ALuint *buffers);
extern void (*alwDeleteEffects)(ALsizei n, const ALuint *effects);
extern void (*alwDeleteFilters)(ALsizei n, const ALuint *filters);
extern void (*alwDeleteSources)(ALsizei n, const ALuint *sources);
extern void (*alwDisable)(ALenum capability);
extern void (*alwDistanceModel)(ALenum distanceModel);
extern void (*alwDopplerFactor)(ALfloat value);
extern void (*alwDopplerVelocity)(ALfloat value);
extern void (*alwEffectf)(ALuint effect, ALenum param, ALfloat flValue);
extern void (*alwEffectfv)(ALuint effect, ALenum param, const ALfloat *pflValues);
extern void (*alwEffecti)(ALuint effect, ALenum param, ALint iValue);
extern void (*alwEffectiv)(ALuint effect, ALenum param, const ALint *piValues);
extern void (*alwEnable)(ALenum capability);
extern void (*alwFilterf)(ALuint filter, ALenum param, ALfloat flValue);
extern void (*alwFilterfv)(ALuint filter, ALenum param, const ALfloat *pflValues);
extern void (*alwFilteri)(ALuint filter, ALenum param, ALint iValue);
extern void (*alwFilteriv)(ALuint filter, ALenum param, const ALint *piValues);
extern void (*alwGenAuxiliaryEffectSlots)(ALsizei n, ALuint *effectslots);
extern void (*alwGenBuffers)(ALsizei n, ALuint *buffers);
extern void (*alwGenEffects)(ALsizei n, ALuint *effects);
extern void (*alwGenFilters)(ALsizei n, ALuint *filters);
extern void (*alwGenSources)(ALsizei n, ALuint *sources);
extern void (*alwGetAuxiliaryEffectSlotf)(ALuint effectslot, ALenum param, ALfloat *pflValue);
extern void (*alwGetAuxiliaryEffectSlotfv)(ALuint effectslot, ALenum param, ALfloat *pflValues);
extern void (*alwGetAuxiliaryEffectSloti)(ALuint effectslot, ALenum param, ALint *piValue);
extern void (*alwGetAuxiliaryEffectSlotiv)(ALuint effectslot, ALenum param, ALint *piValues);
extern ALboolean (*alwGetBoolean)(ALenum param);
extern void (*alwGetBooleanv)(ALenum param, ALboolean *values);
extern void (*alwGetBuffer3f)(ALuint buffer, ALenum param, ALfloat *value1, ALfloat *value2, ALfloat *value3);
extern void (*alwGetBuffer3i)(ALuint buffer, ALenum param, ALint *value1, ALint *value2, ALint *value3);
extern void (*alwGetBufferf)(ALuint buffer, ALenum param, ALfloat *value);
extern void (*alwGetBufferfv)(ALuint buffer, ALenum param, ALfloat *values);
extern void (*alwGetBufferi)(ALuint buffer, ALenum param, ALint *value);
extern void (*alwGetBufferiv)(ALuint buffer, ALenum param, ALint *values);
extern ALdouble (*alwGetDouble)(ALenum param);
extern void (*alwGetDoublev)(ALenum param, ALdouble *values);
extern void (*alwGetEffectf)(ALuint effect, ALenum param, ALfloat *pflValue);
extern void (*alwGetEffectfv)(ALuint effect, ALenum param, ALfloat *pflValues);
extern void (*alwGetEffecti)(ALuint effect, ALenum param, ALint *piValue);
extern void (*alwGetEffectiv)(ALuint effect, ALenum param, ALint *piValues);
extern ALenum (*alwGetEnumValue)(const ALchar *ename);
extern ALenum (*alwGetError)(void);
extern void (*alwGetFilterf)(ALuint filter, ALenum param, ALfloat *pflValue);
extern void (*alwGetFilterfv)(ALuint filter, ALenum param, ALfloat *pflValues);
extern void (*alwGetFilteri)(ALuint filter, ALenum param, ALint *piValue);
extern void (*alwGetFilteriv)(ALuint filter, ALenum param, ALint *piValues);
extern ALfloat (*alwGetFloat)(ALenum param);
extern void (*alwGetFloatv)(ALenum param, ALfloat *values);
extern ALint (*alwGetInteger)(ALenum param);
extern void (*alwGetIntegerv)(ALenum param, ALint *values);
extern void (*alwGetListener3f)(ALenum param, ALfloat *value1, ALfloat *value2, ALfloat *value3);
extern void (*alwGetListener3i)(ALenum param, ALint *value1, ALint *value2, ALint *value3);
extern void (*alwGetListenerf)(ALenum param, ALfloat *value);
extern void (*alwGetListenerfv)(ALenum param, ALfloat *values);
extern void (*alwGetListeneri)(ALenum param, ALint *value);
extern void (*alwGetListeneriv)(ALenum param, ALint *values);
extern void* (*alwGetProcAddress)(const ALchar *fname);
extern void (*alwGetSource3f)(ALuint source, ALenum param, ALfloat *value1, ALfloat *value2, ALfloat *value3);
extern void (*alwGetSource3i)(ALuint source, ALenum param, ALint *value1, ALint *value2, ALint *value3);
extern void (*alwGetSourcef)(ALuint source, ALenum param, ALfloat *value);
extern void (*alwGetSourcefv)(ALuint source, ALenum param, ALfloat *values);
extern void (*alwGetSourcei)(ALuint source,  ALenum param, ALint *value);
extern void (*alwGetSourceiv)(ALuint source,  ALenum param, ALint *values);
extern const ALchar* (*alwGetString)(ALenum param);
extern ALboolean (*alwIsAuxiliaryEffectSlot)(ALuint effectslot);
extern ALboolean (*alwIsBuffer)(ALuint buffer);
extern ALboolean (*alwIsEffect)(ALuint effect);
extern ALboolean (*alwIsEnabled)(ALenum capability);
extern ALboolean (*alwIsExtensionPresent)(const ALchar *extname);
extern ALboolean (*alwIsFilter)(ALuint filter);
extern ALboolean (*alwIsSource)(ALuint source);
extern void (*alwListener3f)(ALenum param, ALfloat value1, ALfloat value2, ALfloat value3);
extern void (*alwListener3i)(ALenum param, ALint value1, ALint value2, ALint value3);
extern void (*alwListenerf)(ALenum param, ALfloat value);
extern void (*alwListenerfv)(ALenum param, const ALfloat *values);
extern void (*alwListeneri)(ALenum param, ALint value);
extern void (*alwListeneriv)(ALenum param, const ALint *values);
extern void (*alwSource3f)(ALuint source, ALenum param, ALfloat value1, ALfloat value2, ALfloat value3);
extern void (*alwSource3i)(ALuint source, ALenum param, ALint value1, ALint value2, ALint value3);
extern void (*alwSourcePause)(ALuint source);
extern void (*alwSourcePausev)(ALsizei n, const ALuint *sources);
extern void (*alwSourcePlay)(ALuint source);
extern void (*alwSourcePlayv)(ALsizei n, const ALuint *sources);
extern void (*alwSourceQueueBuffers)(ALuint source, ALsizei nb, const ALuint *buffers);
extern void (*alwSourceRewind)(ALuint source);
extern void (*alwSourceRewindv)(ALsizei n, const ALuint *sources);
extern void (*alwSourceStop)(ALuint source);
extern void (*alwSourceStopv)(ALsizei n, const ALuint *sources);
extern void (*alwSourceUnqueueBuffers)(ALuint source, ALsizei nb, ALuint *buffers);
extern void (*alwSourcef)(ALuint source, ALenum param, ALfloat value);
extern void (*alwSourcefv)(ALuint source, ALenum param, const ALfloat *values);
extern void (*alwSourcei)(ALuint source, ALenum param, ALint value);
extern void (*alwSourceiv)(ALuint source, ALenum param, const ALint *values);
extern void (*alwSpeedOfSound)(ALfloat value);
extern  ALCboolean (*alwcCaptureCloseDevice)(ALCdevice *device);
extern  ALCdevice* (*alwcCaptureOpenDevice)(const ALCchar *devicename, ALCuint frequency, ALCenum format, ALCsizei buffersize);
extern  void       (*alwcCaptureSamples)(ALCdevice *device, ALCvoid *buffer, ALCsizei samples);
extern  void       (*alwcCaptureStart)(ALCdevice *device);
extern  void       (*alwcCaptureStop)(ALCdevice *device);
extern  ALCboolean (*alwcCloseDevice)(ALCdevice *device);
extern  ALCcontext* (*alwcCreateContext)(ALCdevice *device, const ALCint *attrlist);
extern  void        (*alwcDestroyContext)(ALCcontext *context);
extern  void        (*alwcDestroyContext)(ALCcontext *context);
extern  void        (*alwcDestroyContext)(ALCcontext *context);
extern  ALCdevice*  (*alwcGetContextsDevice)(ALCcontext *context);
extern  ALCcontext* (*alwcGetCurrentContext)(void);
extern  ALCenum    (*alwcGetEnumValue)(ALCdevice *device, const ALCchar *enumname);
extern  ALCenum (*alwcGetError)(ALCdevice *device);
extern  ALCenum (*alwcGetError)(ALCdevice *device);
extern  void           (*alwcGetIntegerv)(ALCdevice *device, ALCenum param, ALCsizei size, ALCint *values);
extern  ALCvoid*   (*alwcGetProcAddress)(ALCdevice *device, const ALCchar *funcname);
extern  const ALCchar* (*alwcGetString)(ALCdevice *device, ALCenum param);
extern  const ALCchar* (*alwcGetString)(ALCdevice *device, ALCenum param);
extern  const ALCchar* (*alwcGetString)(ALCdevice *device, ALCenum param);
extern  ALCboolean (*alwcIsExtensionPresent)(ALCdevice *device, const ALCchar *extname);
extern  ALCboolean (*alwcIsExtensionPresent)(ALCdevice *device, const ALCchar *extname);
extern  ALCboolean (*alwcIsExtensionPresent)(ALCdevice *device, const ALCchar *extname);
extern  ALCboolean  (*alwcMakeContextCurrent)(ALCcontext *context);
extern  ALCdevice* (*alwcOpenDevice)(const ALCchar *devicename);
extern  void        (*alwcProcessContext)(ALCcontext *context);
extern  void        (*alwcProcessContext)(ALCcontext *context);
extern  void        (*alwcProcessContext)(ALCcontext *context);
extern  void        (*alwcProcessContext)(ALCcontext *context);
extern  void        (*alwcSuspendContext)(ALCcontext *context);
